include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    # TODO remove this
    implicit-casts: true
    implicit-dynamic: true
  exclude:
    - 'lib/generated/**'
    - '**.g.dart'
    - 'test/**'
  errors:
    body_might_complete_normally_nullable: false
    unused_element: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    avoid_redundant_argument_values: false
    always_specify_types: false
    sort_pub_dependencies: false

    avoid_dynamic_calls: false

    sort_constructors_first: true
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
    unnecessary_const: true

    use_build_context_synchronously: false
    require_trailing_commas: false
    avoid_relative_lib_imports: false
    always_use_package_imports: false

    # TODO(bin): remove this
    use_key_in_widget_constructors: false
