include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    always_specify_types: false
    sort_pub_dependencies: false

    sort_constructors_first: true
    #    prefer_single_quotes: true
    lines_longer_than_80_chars: false
    unnecessary_const: true
